apiVersion: v1
kind: Service
metadata:
  name: asterisk-web-service
  namespace: asterisk
spec:
  selector:
    app: asterisk-web
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: NodePort
