apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv1
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/root/kube_deployments/dump/asterisk.sql" 
