apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv0
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: db-pv0
  hostPath:
    path: "/root/kube_deployments/mysql" 
