version: '3.7'
services:
  web:
    container_name: php_web
    restart: unless-stopped
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:80"
    networks:
      - default
    volumes:
      - ./web:/var/www/html/
    environment:
      SERVICE_NAME: php_web
      SERVICE_TAGS: dev
  db:
    build:
      context: ./mysqld
      dockerfile: Dockerfile
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: asterisk
#      MYSQL_PASSWORD: asterisk
    volumes:
      - ./mysql:/var/lib/mysql/
      - ./dump/asterisk.sql:/docker-entrypoint-initdb.d/asterisk.sql
    networks:
      - default

