apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: asterisk-web
  name: asterisk-web
  namespace: asterisk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asterisk-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: asterisk-web
    spec:
      containers:
      - image: registry.gitlab.com/home-testing/asterisk_web:latest
        imagePullPolicy: Always
        name: asterisk-web
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: asterisk-web-service
  namespace: asterisk
spec:
  selector:
    app: asterisk-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

